name = "4Y"
author = "OoLunar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cce5b7262275f1d08851d7f1170f9cc695a760b621b9c656963ba10c9a8570a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
datapack-folder = "datapacks"
