name = "4Y"
author = "OoLunar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "990b1fef18c15d40c27d49e6a707e098397be5424ea32f9aa227b8e740e9880a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
datapack-folder = "datapacks"
