name = "4Y"
author = "OoLunar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4308da4fe5d561e31017c9244614f684a16ad5e3b0f767087aa20499ca96c6b9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
datapack-folder = "datapacks"
