name = "4Y"
author = "OoLunar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d91d994e08b445c244116a98ea6377676ea8b101c3d983e85d6bdf0b3232cc28"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
datapack-folder = "datapacks"
